language: "ko-KR"  # 리뷰 결과를 한국어로 출력

tone_instructions: |
  코드 리뷰 시 친절하고 건설적인 의견을 제공하세요.
  코드 품질, 성능, 보안, 유지보수성, 그리고 머신러닝 프로젝트의 특성을 고려해 피드백을 남겨주세요.

reviews:
  profile: "chill"            # 리뷰 스타일: chill(부드럽게), strict(엄격하게) 등 선택 가능
  high_level_summary: true    # 변경사항 요약 활성화
  review_status: true         # 리뷰 상태 표시
  auto_review:
    enabled: true             # 자동 코드리뷰 활성화
    drafts: false             # Draft PR은 리뷰하지 않음
  path_instructions:
    - path: "src/**/*.py"
      instructions: |
        파이썬 머신러닝 코드 리뷰 시 다음 사항을 중점적으로 확인하세요:
        - 데이터 전처리, 모델 학습, 평가, 예측 로직이 명확하게 분리되어 있는지
        - 불필요한 반복문, 비효율적인 연산 등이 없는지
        - 하드코딩된 값 대신 상수/설정 파일을 사용하는지
        - 모델 저장/불러오기, 시드 고정 등 재현성(reproducibility)이 보장되는지
        - 주요 함수/클래스에 docstring이 작성되어 있는지
        - 외부 라이브러리(예: numpy, pandas, scikit-learn, tensorflow, pytorch 등) 사용이 적절한지

    - path: "src/**/*.ipynb"
      instructions: |
        Jupyter Notebook 리뷰 시 다음을 확인하세요:
        - 코드, 설명, 시각화 결과가 논리적으로 잘 구성되어 있는지
        - 코드 셀 실행 순서가 올바른지
        - 불필요한 출력물, 디버깅 코드, 대용량 데이터 출력이 남아있지 않은지

    - path: "requirements*.txt"
      instructions: |
        라이브러리 의존성 파일 리뷰 시 다음을 확인하세요:
        - 불필요한 패키지나 중복 항목이 없는지
        - 버전 명시가 필요한 패키지는 명확하게 지정되어 있는지

    - path: "**/test_*.py"
      instructions: |
        테스트 코드 리뷰 시 다음을 확인하세요:
        - 주요 함수/클래스에 대한 테스트가 충분한지
        - pytest 등 테스트 프레임워크 사용이 적절한지
        - 테스트의 독립성과 재현성이 보장되는지

knowledge_base:
  web_search:
    enabled: true             # 필요시 웹 검색 기반 지식 활용

chat:
  auto_reply: true            # 질문 시 자동 응답

